### ISSUE TITLE
SS4 Support

### ISSUE THREAD

**Issue by leepowelldev** [TheBnl/silverstripe-cookie-consent#1]
Hi. Trying to install this into my project, fairly new to SS4, but everything installed via composer so far has gone into my `vendor` directory. However when I install this it goes into the root directory. Is this correct behaviour or have I missed something?

**Comment by TheBnl** [comment]
Hi Lee,

Yes this is actually the behaviour of SS3, here we don't have many projects running on SS4 (yet) so i started this module for SS3 initially so we could place the module in all live projects to be compliant with the GDPR and the version for SS4 is coming shortly!

**Comment by digitall-it** [comment]
Actually it is the intended behaviour. Not all modules use the new Silverstripe 4 "folder expose feature" that enables them to work out the vendor folder. That doesn't mean the module will not work.

Usually, modules that follow semver (semantic versioning) will have a branch version for Silverstripe 3.x and another one for Silverstripe 4.x, with a major version number that never changes if non breaking functions are added.

So, a way to know which version of the module to pick, is to have a look at his composer.json file. If it lists 4.x, and you have 3.x, you will have to check for a previous version (sometimes this is stated in the README.md file). If the composer.json requires Silverstripe 3.x, and you have the framework at 4.x, it's code is untested with Silverstripe 4. Hope this adds some general tips to the conversation.

**Comment by TheBnl** [comment]
Hi @leepowellcouk  the module supports SS4 form version 2.x forward! 
For SS3 you'll need to pick the 1.x versions!

**Comment by leepowelldev** [comment]
Legend! Thank you 😃
