### ISSUE TITLE
Template Layout Override

### ISSUE THREAD

**Issue by SnowB1** [TheBnl/silverstripe-cookie-consent#11]
Tried to override the page layout and found that I had to put the override into 

templates/Broarm/CookieConsent/CookiePolicyPage.ss templates/Broarm/CookieConsent/CookieConsentCheckboxField_holder.ss

Instead of templates/Layout and templates/Includes

**Comment by TheBnl** [comment]
Hi SnowB1,

Thats true, with namespaced modules you'll have to place the templates in the corresponding folder path. Are you experiencing this on an SS3 site or an SS4 one? This module was written in the transition period to SS4 so the SS3 version also uses these namespaces.
