### ISSUE TITLE
Configure domain & path variables for the cookie

### ISSUE THREAD

**Issue by Kefisu** [TheBnl/silverstripe-cookie-consent#19]
Hi,

For a specific use case I am required to configure the domain & path for the `cookie::set()` function. I couldn't find any option to configure this using the yml and in the sourcecode I only found that `null` is being passed to these parameters.

**Comment by TheBnl** [comment]
Hi Kevin,

Indeed, it would be a nice addition, unforunatly i haven't gotten around to it yet.
It should be as simple as changing the `CookieConsent::setConsent` method to something like:
```php
public static function setConsent($consent)
{
    $consent = array_filter(array_unique(array_merge($consent, self::config()->get('required_groups'))));
    $domain = self::config()->get('domain') ?: null;
    Cookie::set(CookieConsent::COOKIE_NAME, implode(',', $consent), 730, null, $domain, false, false);
}
```

Then you would be able configure a custom domain in your yml config.
```yml
Broarm\CookieConsent\CookieConsent:
  domain: '.example.org'
```

If you'd like you could create a PR with the addition?

**Comment by TheBnl** [comment]
Iv'e create the PR since it's such a simple addition, could you test it in the project your working on?
If you change your composer to use the branch "configure-domain" you should be able to test the feature.

**Comment by Kefisu** [comment]
It works like a charm! 

Thank you for the addition

**Comment by TheBnl** [comment]
Awesome! Thanks for the feedback. I'll merge it into the master and tag it
