### ISSUE TITLE
Add $singular_name to the pages

### ISSUE THREAD

**Issue by PVerberkmoes** [TheBnl/silverstripe-cookie-consent#34]
The problem now is that in the SiteTree the "CookiePolicyPage" and the "PrivacyPolicyPage" appear as Content Page.
![Screenshot 2021-08-06 at 09 36 07](https://user-images.githubusercontent.com/25683222/128474339-38eb976b-d21f-4e0f-b95d-1caf9edd31d2.png)

**Comment by TheBnl** [comment]
I'm not able to reproduce this issue. SilverStripe should, by default, fallback to the class name if no $singular_name is set.
Could it be that you've overwritten the method `singular_name()` ? A better option would be to set this in a translation file as such:

```
nl:
  Page: 
    SINGULARNAME: 'Content pagina'
```
